version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-challenge-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13q1xxsogpu6o"
s3_prefix = "resume-challenge-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
