# This is a basic workflow to help you get started with Actions

name: master

# Controls when the workflow will run
on: push
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  
# on:
#   push:
#     branches:
#     - master

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  master-infra:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 2
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: py setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
      - name: Run test suite
        run: |
            pipenv run test -v

      # - name: unit tests
      #   run: python -m pytest


  build-and-deploy-infra:
    needs: master-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-secret-access-key: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1
      - run: sam build --use-container
        # working-directory: cloud-resume-challenge
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        # working-directory: cloud-resume-challenge
  

  build-and-deploy-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-files-2
    permissions:
      id-token: write
      contents: read
      
    steps:
      - uses: actions/checkout@master
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-secret-access-key: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1
      - uses: actions/setup-node@v2
        with:
          node-version:  14.x
          cache: "npm"
          cache-dependency-path: ' **/package-lock.json'
      - run: |
             npm ci 
             npm run build --if-present 
             npm run deploy
             aws cloudfront create-invalidation --distribution-id E3O5MGQ019VZMJ --paths "/*"


        

      